# hugo.toml ç¤ºä¾‹
baseURL = "https://MU-GONG-SONG.github.io/blog/"
publishDir = "public"   # Hugo æ„å»ºè¾“å‡ºç›®å½•
title = "Q-song | æŠ€æœ¯.ç”Ÿæ´».é˜…è¯».æ€è€ƒ"
theme = "PaperMod"
languageCode = "zh"
defaultContentLanguage = "zh"

enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = true
buildExpired = false
enableEmoji = true
googleAnalytics = "G-MZJS5SGFET"

[minify]
disableXML = true
minifyOutput = true

# menu.main æ•°ç»„è¡¨æ ¼å†™æ³•
[[menu.main]]
name = "ğŸ” æœç´¢"
url = "search/"
weight = 9

[[menu.main]]
name = "â±ï¸ æ—¶é—´è½´"
url = "archives"
weight = 10

[[menu.main]]
name = "â›©ï¸ åˆ†ç±»"
url = "categories/"
weight = 20

[[menu.main]]
name = "ğŸ§© æ ‡ç­¾"
url = "tags/"
weight = 30

[[menu.main]]
name = "ğŸ™‹ğŸ»â€â™‚ï¸ å…³äº"
url = "about"
weight = 50

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
env = "production"
description = "ä¸ªäººåšå®¢"
author = "Mumu"
defaultTheme = "auto"
disableThemeToggle = false
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = false
ShowCodeCopyButtons = true
ShowToc = true

[params.homeInfoParams]
Title = "æ‚Ÿå·²å¾€ä¹‹ä¸è°ï¼ŒçŸ¥æ¥è€…ä¹‹å¯è¿½"
Content = """
- âœ¨ æ¬¢è¿æ¥åˆ°æˆ‘çš„ä¸ªäººåšå®¢

- ğŸ¤” æˆ‘åœ¨è¿™é‡Œåˆ†äº«æŠ€æœ¯ã€è¯»ä¹¦ã€ç”Ÿæ´»è¿˜æœ‰æ€è€ƒã€‚
"""

# socialIcons æ•°ç»„è¡¨æ ¼
[[params.socialIcons]]
name = "Github"
url = "https://github.com/MU-GONG-SONG"

[[params.socialIcons]]
name = "RSS"
url = "index.xml"

[[params.socialIcons]]
name = "email"
url = "mailto:1293589405@qq.com"

[params.label]
text = "Q-song"
icon = "img/è¶³è¿¹.png"
iconHeight = 35

[markup.goldmark.renderer]
unsafe = true
